import os
from datetime import datetime

from graph.state import AgentState
from tools.llm import complete

_DEFAULT_OUTPUTS = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs")


def _outputs_dir() -> str:
    return os.environ.get("DS_OUTPUTS_DIR", _DEFAULT_OUTPUTS)

SYSTEM_PROMPT = """You are a Technical Report Writer. Your job is to compile a complete, professional data science report in markdown from the outputs of the engineering, analysis, and review agents.

## Report Structure

Write the report with these exact sections in this order:

# [Descriptive Title]

## Executive Summary
Two to three sentences answering the original question directly. Lead with the most important finding and the key number (e.g., "The Random Forest model achieved 87.3% test accuracy...").

## Problem Statement
Restate what was asked, what dataset was used, and what the success criteria are.

## Data
- Source and acquisition method
- Raw shape (rows × columns)
- Key features (list with types)
- Cleaning steps performed and their impact (e.g., "Dropped 183 rows with missing Age; imputed 2 with median")
- Final cleaned shape

## Methodology
A numbered list of the steps taken in order, citing which agent performed each. Keep it high-level but specific.

## Findings

### Exploratory Analysis
Key patterns found: class balance, notable correlations, interesting distributions. Reference specific numbers from the output logs.

### Statistical Analysis (if applicable)
Test results with exact statistics: t-statistic, p-value, effect size. State whether the null hypothesis was rejected.

### Model Results
A markdown table of model(s) evaluated:

| Model | Train Acc | Test Acc | F1 | AUC |
|-------|-----------|----------|----|-----|
| ...   | ...       | ...      | ...| ... |

Note the best model and why it was selected.

## Visualizations
List each PNG file generated with a one-sentence description of what it shows:
- `filename.png` — description

## Review Notes
If a review was performed, summarise the issues found and whether they were addressed.

## Conclusions & Recommendations
- What does this analysis mean in practice?
- What should be done next (more data, different model, deeper analysis)?
- Any caveats or limitations of the current analysis?

---
*Generated by DS Multi-Agent System*

## Writing Rules

- Use exact numbers from the output logs — never round unless stating it
- Use markdown tables for any comparison of multiple values
- Be precise and professional — avoid vague language like "the results were good"
- Do not invent numbers or findings that are not in the output logs
- If a section has no data (e.g., no statistical tests were run), write "Not performed in this run."
"""


def reporter_node(state: AgentState) -> dict:
    # Agents write to 'outputs/' relative to their CWD (the run dir), so all
    # generated files land in run_dir/outputs/ — scan and save there.
    outputs_dir = os.path.join(_outputs_dir(), "outputs")
    os.makedirs(outputs_dir, exist_ok=True)

    context_parts = [
        f"PROBLEM:\n{state['problem']}",
        f"PLAN:\n{state.get('plan', 'N/A')}",
    ]

    history = state.get("code_history", [])
    if history:
        context_parts.append("FULL CODE HISTORY:")
        for i, entry in enumerate(history, 1):
            label = entry.get("agent", "agent").upper()
            context_parts.append(f"### Step {i} [{label}]: {entry['task']}")
            context_parts.append(f"```python\n{entry['code']}\n```")
            if entry["output"]:
                context_parts.append(f"Output:\n```\n{entry['output']}\n```")
            if entry["error"]:
                context_parts.append(f"Error:\n```\n{entry['error']}\n```")

    reviews = state.get("reviews", [])
    if reviews:
        context_parts.append("REVIEWS:\n" + "\n\n---\n\n".join(reviews))

    plots = sorted(f for f in os.listdir(outputs_dir) if f.endswith(".png")) if os.path.isdir(outputs_dir) else []
    if plots:
        context_parts.append(f"GENERATED PLOTS: {', '.join(plots)}")

    report_md = complete(SYSTEM_PROMPT, "\n\n".join(context_parts), max_tokens=8192)

    os.makedirs(outputs_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(outputs_dir, f"report_{timestamp}.md")

    with open(report_path, "w") as f:
        f.write(report_md)

    return {
        "report_path": report_path,
        "final_summary": f"Report saved to {report_path}",
    }
